[project]
name = "arxiv2title"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pymupdf",
]


[project.scripts]
arxiv2title = "arxiv2title:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
